version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: coveralls
    versions:
    - 3.0.0
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
