# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-01-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20170306_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Story',
            name='blurb',
            field=models.TextField(null=True, blank=True),
        ),
    ]
